name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build Gatsby Site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Gatsby Site
      uses: jzweifel/gatsby-cli-github-action@master
      with:
        gatsby-arg: build
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: s080.cyon.net/public_html/dev
        ftp-username: sommern2
        ftp-password: ${{ secrets.FTP_PASSWORD }}
