name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Build Gatsby
      uses: jzweifel/gatsby-cli-github-action@master
      with:
        gatsby-arg: build
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: s080.cyon.net/public_html/dev
        ftp-username: sommern2
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: public
