name: CI

on:
  push:
    branches: [ prod ]
  repository_dispatch:
    types: dispatch

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout prod
      uses: actions/checkout@v2
      with:
        ref: prod
        persist-credentials: false
    - run: ls -la
    - name: Set Node.js
      uses: actions/setup-node@master
      with:
        node-version: 12.x
      #uses: jzweifel/gatsby-cli-github-action@master
      #with:
        #gatsby-arg: build
    - name: Install dependencies
      run: yarn install --prod --pure-lockfile
    - name: Build
      run: yarn run build
    - run: ls -la public
    - name: FTP deploy
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: s080.cyon.net/public_html/2020-gatsby
        ftp-username: sommern2
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: public
