name: CI

on:
  push:
    branches: [ prod ]
  repository_dispatch:
    types: dispatch

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout prod
    - uses: actions/checkout@v2
      with:
        ref: prod
        persist-credentials: false
    - name: Setup Node
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: ls -la
    - name: Build gatsby
      uses: jzweifel/gatsby-cli-github-action@master
      with:
        gatsby-arg: build
    - run: ls -la public
    - name: FTP deploy
      # uses: SamKirkland/FTP-Deploy-Action@3.1.1
      # with:
        # ftp-server: s080.cyon.net/public_html/2020-gatsby
        # ftp-username: sommern2
        # ftp-password: ${{ secrets.FTP_PASSWORD }}
        # local-dir: public
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.1.0
      with:
        ftp_host: ${{ secrets.FTP_HOST }}
        ftp_username: ${{ secrets.FTP_USER }}
        ftp_password: ${{ secrets.FTP_PASSWORD }}
        local_source_dir: "public"
        dist_target_dir: "/public_html/2020-gatsby"
        delete: "true"
